### ISSUE TITLE
`ctrl - y` copy empty icon.

### ISSUE THREAD

**Issue by miraculusik** [glepnir/nerdicons.nvim#3]

**Comment by glepnir** [comment]
how you trigger that give me a reproduce step.

**Comment by miraculusik** [comment]
> how you trigger that give me a reproduce step.

In neovim typing `:NerdIcons` and the floating window opens
after typing name of icon. I am selecting icon with CTRL + y However, the icon is not selected, the values that I used before appear on the clipboard.

**Comment by miraculusik** [comment]
I found the cause of the problem. It was related with my config.
`vim.opt.clipboard:append("unnamedplus")`
I am using this config for copying content and access my system clipboard. I removed this config and now plugin work perfectly. 
sorry for opening this issue this was my fault 😅. Plugin works perfectly 😃

**Comment by dror-g** [comment]
this is an issue for me as well. I think it's because I have `use_system_clipboard = true` set.   
C-y simply does not copy. I get whatever I last copied to clipboard when pasting.  
Can you please suggest a workaround?  
  
Perhaps worth noting that if I use mouse to highlight and copy an icon from NerdIcons floating window - it goes crazy.  
C-n / C-p stop working, can't quit it unless I hit esc and `:q!` in cmd gutter, once for results float, and again for search line float.  
  
Thank you! great plugin.
